apiVersion: v1
kind: ConfigMap
metadata:
  name: nef-configmap
data:
  DOMAIN: localhost
  DOCKER_IMAGE_BACKEND: dimfrag/nef-backend
  BACKEND_TAG: "1.0"
  DOCKER_IMAGE_FRONTEND: frontend
  SERVER_NAME: localhost
  SERVER_HOST: localhost
  SERVER_PORT: "8888"
  BACKEND_CORS_ORIGINS: '["https://5g-api-emulator.medianetlab.eu","http://localhost"]'
  PROJECT_NAME: NEF_Emulator
  SECRET_KEY: 2D47CF2958CEC7CC86C988E9F9684
  FIRST_SUPERUSER: admin@my-email.com
  FIRST_SUPERUSER_PASSWORD: pass
  SMTP_TLS: "True"
  SMTP_PORT: "465"
  SMTP_HOST: mail.host.com
  SMTP_USER: user
  SMTP_PASSWORD: pass
  EMAILS_FROM_EMAIL: user@my-email.com
  SENTRY_DSN: ""
  USERS_OPEN_REGISTRATION: "true"
  NEF_HOST: 3gppnef
  POSTGRES_SERVER: db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pass
  POSTGRES_DB: app
  PGADMIN_LISTEN_PORT: "5050"
  PGADMIN_DEFAULT_EMAIL: admin@my-email.com
  PGADMIN_DEFAULT_PASSWORD: pass
  MONGO_USER: root
  MONGO_PASSWORD: pass
  MONGO_CLIENT: mongodb://mongo_nef:27017/
  MONGO_EXPRESS_ENABLE_ADMIN: "true"
  ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo-nef:27017/
  DOCKER_IMAGE_PROXY: dimfrag/nef-nginx
  PROXY_TAG: "1.0"
  NGINX_HTTP: "8090"
  NGINX_HTTPS: "4443"
  CAPIF_HOST: capifcore
  CAPIF_HTTP_PORT: "8080"
  CAPIF_HTTPS_PORT: "443"
  EXTERNAL_NET: "false"
  USE_PUBLIC_KEY_VERIFICATION: "false"